# Claim Radius in Blocks
claimRadius: 64

# Minimum distance from the center of one Region to the centers of other Regions
minimumDistance: 272

# Use our custom Lodestone Recipe?
useCustomRecipe: true

# Automatically set Title on Entry Flag?
setTitleFlag: true

# Clear "Sorry! You are not allowed to ___ here!" Message from WorldGuard by default?
clearDenyMessage: true

# Unclaim confirm Time in Seconds
unclaimTime: 10
